### ISSUE TITLE
CustomFields require `name` not `field`

### ISSUE THREAD

**Issue by CristhianMotoche** [jakesen/pyhatchbuck#18]
Hi! I'm using the library and I found an error with `CustomFields`:

```
    • Custom Fields
        a. Value for Custom fields can be specified with name or id of custom fields as follows:
 "customFields": [
                {
            "name": "Anniversary",
            "value": "Yes"
        },{
            "value": "No",
            "id": "MEl6aFhhWmVzTlpZbnFpTFQ0Q2czb2hDd0pzQkhVNFJqcVVORnhkbExRSTE1"
        }]
```

Currently, [`CustomFields`](https://github.com/jakesen/pyhatchbuck/blob/master/hatchbuck/objects.py#L19) require `field` and `value`, but the API is expecting `name` and `value`.

I suppose the change is really straight forward: replace `field` with `name`. I'll try to submit a PR.

**Comment by jakesen** [comment]
That would be great! I don't think I ever actually got around to testing the custom fields. If possible it would be great if we could also add test coverage for custom fields to demonstrate that they are working correctly.
