### ISSUE TITLE
Use pyhatchbuck with python3

### ISSUE THREAD

**Issue by lopenchi** [jakesen/pyhatchbuck#22]
I saw that this library is available for` python >=2.7, <3.0`

Have you thought about making this library available for new version of python, exactly `python >= 3.7` ?

**Comment by jakesen** [comment]
I think I originally planned on adding Python 3 compatibility, and then I got so busy with other things I never did. It definitely needs to work with Python 3 to be a viable library these days, since most new Python projects require it.

**Comment by lopenchi** [comment]
Hi @jakesen . 
Do you have defined an ETA for solving this issue.
Nowadays, I'm working in the migration of a project for py2 to py3. 
The project uses this library, that is why we need this library to have a compatibility for py2 and py3.  

If you are too busy, I could help you to migrate it , or we could work together to have this lib available for py3 asap.

**Comment by jakesen** [comment]
@lopenchi If you have time and want to start working on it that would be great! I am pretty busy this week, but I might have time to work on it next week.

**Comment by jakesen** [comment]
@lopenchi Thanks for your help with this! The new build version 0.3 with Python 3.7 support has been published to PyPi.

**Comment by jakesen** [comment]
Actually it will be version 0.4
